In [1]:
import numpy, cv2

In [2]:
im_g = cv2.imread("smallgray.png", 0) # non RGB image

In [4]:
im_g

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [7]:
im_g2 = cv2.imread("smallgray.png", 1) # RGB image
im_g2

array([[[187, 187, 187],
        [158, 158, 158],
        [104, 104, 104],
        [121, 121, 121],
        [143, 143, 143]],

       [[198, 198, 198],
        [125, 125, 125],
        [255, 255, 255],
        [255, 255, 255],
        [147, 147, 147]],

       [[209, 209, 209],
        [134, 134, 134],
        [255, 255, 255],
        [ 97,  97,  97],
        [182, 182, 182]]], dtype=uint8)

In [11]:
img_3 = cv2.imread("btc.png", 1)
img_3

array([[[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [245, 245, 245],
        [245, 245, 245],
        [245, 245, 245]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [245, 245, 245],
        [245, 245, 245],
        [245, 245, 245]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [245, 245, 245],
        [245, 245, 245],
        [245, 245, 245]],

       ...,

       [[245, 245, 245],
        [245, 245, 245],
        [245, 245, 245],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[245, 245, 245],
        [245, 245, 245],
        [245, 245, 245],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[245, 245, 245],
        [245, 245, 245],
        [245, 245, 245],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]]

In [10]:
new_image = cv2.imwrite("newsmallgray.png", img_3)